on: [push, pull_request]
name: CITest
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up snyk cli
      uses: snyk/actions/setup@master
    - name: Run Snyk scans to check for vulnerabilities
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: get1.17
      run: |
        go version
        go get golang.org/dl/go1.17beta1
        go1.17beta1 download
    - name: UnitTest
      run: go test -count=2 -v ./...
    - name: BenchMarkTest
      run: go test -cpu=1 -bench=. -run='^$' ./...
    - name: BenchMarkTest1.17
      run: go1.17beta1 test -cpu=1 -bench=. -run='^$' ./...
    - name: Generate coverage report
      run: |
        go test -race -covermode=atomic -coverprofile="coverage.txt"
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-lru-cache